export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const CLEAR_STORE = "CLEAR_STORE";
export const CHANGE_HOW_TO_USE_VISIBILITY = "CHANGE_HOW_TO_USE_VISIBILITY";
